name = "emui"
main = "worker.js"
compatibility_date = "2026-01-28"
kv_namespaces = [
  { binding = "ENI_KV", id = "e7814f6a703047dbb2c1adcf634cee2d" }
]
[observability]
[observability.logs]
enabled = false
invocation_logs = true